# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zipkok' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'Alamofire', '~> 5.2'
  pod "MBCircularProgressBar"
  # Pods for zipkok

end
