# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zipkok' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'KakaoSDKUser'  # 사용자 관리
  pod 'Firebase/Analytics', '7.2-M1'
  pod 'Firebase/Messaging', '7.2-M1'
  pod 'Alamofire', '~> 5.2'
  pod 'MBCircularProgressBar'
  pod 'SwiftKeychainWrapper'
  pod 'Toast-Swift', '~> 5.0.1'
  # Pods for zipkok
end
